---
name: kuberos

kubeApiServerUrl: {{ env.KUBE_API_SERVER_URL }}
kubeApiServerCaData: {{ env.KUBE_API_SERVER_CA }}

oidcIssuerUrl: https://accounts.google.com
oidcClientId: {{ env.OIDC_CLIENT_ID }}
oidcClientSecret: {{ env.OIDC_CLIENT_SECRET }}

tlsCertificateArn: arn:aws:acm:us-east-1:914373874199:certificate/eef979df-e176-4dca-bb38-e035bee14d51

profiles:
  dev:
    clusterName: kube1
    name: {{ branch.replace('/', '-') }}
    namespace: sbx
  prd:
    clusterName: kube1
    namespace: kube-system

branches:
  master: prd
  dev/*:  dev
