---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberos-config
  namespace: {{ build.profile.namespace }}
data:
  secret: {{ service.oidcClientSecret }}
  template: |-
    ---
    apiVersion: v1
    kind: Config
    clusters:
      - name: {{ build.profile.clusterName }}
        cluster:
          certificate-authority-data: {{ service.kubeApiServerCaData }}
          server: {{ service.kubeApiServerUrl }}
    current-context: {{ build.profile.clusterName }}
