---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kuberos
  name: kuberos
  namespace: {{ build.profile.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ service.tlsCertificateArn }}"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "*"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 10003
  selector:
    k8s-app: kuberos
