---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberos-config
  namespace: {{ build.profile.namespace }}
data:
  secret: {{ service.oidcClientSecret }}
  template: |-
    ---
    apiVersion: v1
    kind: Config
    current-context: {{ build.profile.clusterName }}
    clusters:
    - name: {{ build.profile.clusterName }}
      cluster:
        certificate-authority-data: {{ service.kubeApiServerCaData }}
        server: {{ service.kubeApiServerUrl }}
